# Generated by Django 5.2.8 on 2026-01-15 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='column',
            unique_together=set(),
        ),
    ]
