# Generated by Django 5.2.8 on 2025-12-02 03:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member'), ('guest', 'Guest')], default='member', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'memberships',
                'ordering': ['-joined_at'],
            },
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('workspace_type', models.CharField(choices=[('personal', 'Personal'), ('team', 'Team'), ('organization', 'Organization')], default='team', max_length=20)),
                ('invite_code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('members', models.ManyToManyField(related_name='workspaces', through='workspaces.Membership', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_workspaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workspaces',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='membership',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='workspaces.workspace'),
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['invite_code'], name='workspaces_invite__7e5dba_idx'),
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['owner'], name='workspaces_owner_i_04111b_idx'),
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['is_active'], name='workspaces_is_acti_88a65d_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['user', 'workspace'], name='memberships_user_id_45b3e7_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['role'], name='memberships_role_9d7025_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('user', 'workspace')},
        ),
    ]
