# Generated by Django 5.2.8 on 2025-12-02 03:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('archive', 'Archived'), ('restore', 'Restored'), ('move', 'Moved'), ('assign', 'Assigned'), ('comment', 'Commented'), ('upload', 'Uploaded')], max_length=20)),
                ('entity_type', models.CharField(choices=[('workspace', 'Workspace'), ('project', 'Project'), ('task', 'Task'), ('comment', 'Comment'), ('file', 'File'), ('column', 'Column')], max_length=50)),
                ('entity_id', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='projects.project')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'activity_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace', 'created_at'], name='activity_lo_workspa_a8c8f5_idx'), models.Index(fields=['project', 'created_at'], name='activity_lo_project_80b048_idx'), models.Index(fields=['user'], name='activity_lo_user_id_072db3_idx'), models.Index(fields=['entity_type', 'entity_id'], name='activity_lo_entity__5a4970_idx')],
            },
        ),
    ]
